### ISSUE TITLE
Ollie Cover block CSS overrides min-height setting on small viewports

### ISSUE THREAD

**Issue by mrwweb** [OllieWP/ollie#183]
**Describe the bug**
[This CSS ruleset](https://github.com/OllieWP/ollie/blob/637321db6197f861f920be6fd4f98390e777b3ed/assets/styles/core-cover.css#L27) takes precedence over the inline style generated by the Cover Block's min-height setting:

```css
@media (max-width: 781px) {
	.wp-block-cover:not(.has-aspect-ratio) {
		min-height: 430px !important;
	}
}
```

## Real-World Use Case

I need to use the Cover Block in my header for it's background and overlay controls. I do not want a min-height for my site header of 430px.

## To Reproduce

- Make a cover block with no content or very brief content
- Change its minimum height in the settings sidebar to something really small (50px)
- View the page and change the browser window to be less than 781px

**Result:** The cover block is at least 430px tall.

## Expected behavior

The Cover Block's min height setting should be respected

## Potential Solution

Untested, but this is probably what I would do:

```css
@media (max-width: 781px) {
	.wp-block-cover:not(.has-aspect-ratio,[style*="min-height"]) {
		min-height: 430px !important;
	}
}
```

I'm pretty sure that wouldn't increase the specificity, so it should be a fairly safe change as well.

## Details

- Ollie 1.4.2
- WordPress 6.7.2

**Comment by ph17ur** [comment]
Just hit this independently on a couple of sites, so wanted to add a confirmed second case plus a tested fix.

My case: slightly different symptom, same root cause. Landing page template (no header/footer), Cover block set to full height (100vh) via the editor. On mobile the 430px override kicks in, the Cover shrinks, and because there's nothing below it to fill the remainder, you're left with a chunk of blank whitespace at the bottom of the page — the document ends up shorter than the viewport.

Fix I've tested and confirmed working, though it's narrower than @mrwweb's — it only re-asserts height on Covers explicitly set to 100vh, rather than excluding any Cover with an inline min-height:

```css
@media (max-width: 781px) {
    .wp-block-cover[style*="min-height:100vh"] {
        min-height: 100dvh !important;
    }
}
```

@mrwweb's proposed fix looks like the better general solution since it respects any custom min-height value, not just 100vh — mine's more of a targeted patch for the full-height use case specifically. Either way, seems like this could do with a proper fix in core-cover.css rather than everyone patching around it individually.

Happy to test a PR against either approach if that's useful.
